### ISSUE TITLE
Investigate flaky tests (timebox 2 days)

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-design-system#1957]
## What

Investigate tests that sometimes fail - for instance see the following workflow runs:

- https://github.com/alphagov/govuk-design-system/runs/3757974430?check_suite_focus=true
- https://github.com/alphagov/govuk-design-system/runs/3894638756?check_suite_focus=true

It is not clear why they are failing or if it is fixable, so this work should be timeboxed to maximum two days.

## Why

Flaky tests mean confusion for contributors, and can also cause issues if they happen post-merge (see https://github.com/alphagov/design-system-team-internal/issues/527). We should try and fix them, if we can.

## Who needs to work on this

Developer

## Who needs to review this

Developer

## Done when

- [ ] Find instances of flaky tests
- [ ] Investigate cause for failure
- [ ] Fix if possible

**Comment by lfdebrux** [comment]
Another example of a test run with a flaky failure:

https://github.com/alphagov/govuk-design-system/runs/4950634265?check_suite_focus=true

```
FAIL __tests__/component-options.test.js
  ● Component page › macro options should be opened and in view when linked to

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      71 |     // Check if the example has been scrolled into the viewport
      72 |     const $example = await page.$('#options-back-link-example')
    > 73 |     expect(await $example.isIntersectingViewport()).toBe(true)
         |                                                     ^
      74 |   })
      75 |
      76 |   it('macro options subtable should be opened and in view when linked to', async () => {

      at Object.<anonymous> (__tests__/component-options.test.js:73:53)
          at runMicrotasks (<anonymous>)
```

**Comment by domoscargin** [comment]
The original failures in the issue description have had their logs deleted due to retention limits, so here's another recent failure:

```
FAIL __tests__/search.test.js ([36](https://github.com/alphagov/govuk-design-system/runs/5452041339?check_suite_focus=true#step:7:36).145 s)
  ● Site search › does not return any results when searching for something that does not exist

    thrown: "Exceeded timeout of 10000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      20 |
      21 | describe('Site search', () => {
    > 22 |   it('does not return any results when searching for something that does not exist', async () => {
         |   ^
      23 |     await page.goto(baseUrl, { waitUntil: 'load' })
      24 |
      25 |     await page.waitForSelector('.app-site-search__input')

      at __tests__/search.test.js:22:3
      at Object.<anonymous> (__tests__/search.test.js:21:1)
```

https://github.com/alphagov/govuk-design-system/runs/5452041339?check_suite_focus=true

**Comment by domoscargin** [comment]
And more:

```
FAIL __tests__/cookie-banner.test.js (24.341 s)
  ● Cookie banner › is hidden on the cookies page

    thrown: "Exceeded timeout of 10000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      28 |   })
      29 |
    > [30](https://github.com/alphagov/govuk-design-system/runs/5451880279?check_suite_focus=true#step:7:30) |   it('is hidden on the cookies page', async () => {
         |   ^
      [31](https://github.com/alphagov/govuk-design-system/runs/5451880279?check_suite_focus=true#step:7:31) |     await page.setCookie({ name: 'design_system_cookies_policy', value: '{"analytics":true, "version":1}', url: baseUrl })
      [32](https://github.com/alphagov/govuk-design-system/runs/5451880279?check_suite_focus=true#step:7:32) |     await page.goto(`${baseUrl}/cookies/`, { waitUntil: 'load' })
      [33](https://github.com/alphagov/govuk-design-system/runs/5451880279?check_suite_focus=true#step:7:33) |

      at __tests__/cookie-banner.test.js:30:3
      at Object.<anonymous> (__tests__/cookie-banner.test.js:12:1)
          at runMicrotasks (<anonymous>)

  ● Cookie banner › when JavaScript is enabled › is hidden if the consent cookie version is valid

    thrown: "Exceeded timeout of 10000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      59 |     })
      60 |
    > 61 |     it('is hidden if the consent cookie version is valid', async () => {
         |     ^
      62 |       await page.setCookie({ name: 'design_system_cookies_policy', value: '{"analytics":true, "version":1}', url: baseUrl })
      63 |       await page.goto(`${baseUrl}`, { waitUntil: 'load' })
      64 |       const isCookieBannerHidden = await page.waitForSelector(COOKIE_BANNER_SELECTOR, { visible: false })

      at __tests__/cookie-banner.test.js:61:5
      at __tests__/cookie-banner.test.js:[47](https://github.com/alphagov/govuk-design-system/runs/5451880279?check_suite_focus=true#step:7:47):3
      at Object.<anonymous> (__tests__/cookie-banner.test.js:12:1)
```

https://github.com/alphagov/govuk-design-system/runs/5451880279?check_suite_focus=true

**Comment by domoscargin** [comment]
And another:

```
● Site search › returns results where a word in the title begins with the letter "d"

    expect(received).toBeTruthy()

    Received: false

      42 |     )
      43 |     // regex with word boundary, in our case words that begin with 'd'
    > 44 |     expect(resultsArray.every(item => (/\b[d]\w*/).test(item))).toBeTruthy()
         |                                                                 ^
      [45](https://github.com/alphagov/govuk-design-system/runs/5451947488?check_suite_focus=true#step:7:45) |   })
      [46](https://github.com/alphagov/govuk-design-system/runs/5451947488?check_suite_focus=true#step:7:46) |   it('returns results that contain aliases that start with the letter "d"', async () => {
      [47](https://github.com/alphagov/govuk-design-system/runs/5451947488?check_suite_focus=true#step:7:47) |     await page.goto(baseUrl, { waitUntil: 'load' })

      at Object.<anonymous> (__tests__/search.test.js:44:65)
```

https://github.com/alphagov/govuk-design-system/runs/5451947488?check_suite_focus=true

**Comment by domoscargin** [comment]
Pushed a change to [retry flaky tests](https://github.com/alphagov/govuk-design-system/pull/2304). We can keep an eye on it and see if there's still issues. This is very much the "nothing to see here" approach to dealing with this.

**Comment by domoscargin** [comment]
We've made quite a few changes to our testing tools (mostly in terms of bumping dependencies), and haven't noticed any issues with tests for a while, so I'm going to close this and we can reopen if we notice things getting flaky again.

https://github.com/alphagov/govuk-design-system/pull/2532

**Comment by domoscargin** [comment]
Got another of these (in Windows):

```bash
FAIL  __tests__/search.test.js
  ● Site search › returns results where a word in the title begins with the letter "d"

    expect(received).toBeTruthy()

    Received: false

      53 |
      54 |     // regex with word boundary, in our case words that begin with 'd'
    > 55 |     expect(resultsArray.every(item => (/\b[d]\w*/).test(item))).toBeTruthy()
         |                                                                 ^
      56 |   })
      57 |
      58 |   it('returns results that contain aliases that start with the letter "d"', async () => {

      at Object.toBeTruthy (__tests__/search.test.js:55:65)


Error: expect(received).toBeTruthy()

Received: false
```
