### ISSUE TITLE
Design System does not build in Windows environment

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#598]
"I'm trying to get the design system up and running locally, as I want to try it for a concept for something. I'm using node 8.9.4, cloned the repo, ran npm install - ok, but when i run npm start, it errors as below snippet. However, as I can see, the files exist in src."

```
Error: File not available: javascripts/application-ie8.js
    at get_js_files (C:\GitHub\IxDDocumentation\govuk-design-system\node_modules\metalsmith-uglify\index.js:54:23)
    at Ware.main (C:\GitHub\IxDDocumentation\govuk-design-system\node_modules\metalsmith-uglify\index.js:167:23)
    at Ware.<anonymous> (C:\GitHub\IxDDocumentation\govuk-design-system\node_modules\wrap-fn\index.js:45:19)
    at next (C:\GitHub\IxDDocumentation\govuk-design-system\node_modules\ware\lib\index.js:85:20)
    at C:\GitHub\IxDDocumentation\govuk-design-system\node_modules\wrap-fn\index.js:121:18
    at finalize (C:\GitHub\IxDDocumentation\govuk-design-system\node_modules\metalsmith-rollup\lib\index.js:49:16)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! govuk_design_system@ start: `node tasks/serve.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the govuk_design_system@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I've also had other reports that people have tried to build this on Windows and failed.

**Comment by igloosi** [comment]
i guess build all paths with `path`

**Comment by nickcolley** [comment]
Yeah I think the first step would be to get Travis CI in Windows working, so fingers crossed that happens soon :P

**Comment by joelanman** [comment]
Looks like it's this:

https://github.com/borisovg/metalsmith-uglify/issues/20

**Comment by ljelewis** [comment]
I'm having this issue also.

Does anyone know of a temporary workaround?

**Comment by joelanman** [comment]
@nickcolley these lines? https://github.com/alphagov/govuk-design-system/blob/master/lib/metalsmith.js#L174-L186
